# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\x12\x0cgTaskmanager\"\x07\n\x05\x45mpty\"\x14\n\x02ID\x12\x0e\n\x06taskId\x18\x01 \x01(\x05\"\x92\x01\n\x0bTaskDetails\x12 \n\x06taskId\x18\x01 \x01(\x0b\x32\x10.gTaskmanager.ID\x12\x11\n\ttaskTitle\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12(\n\x06status\x18\x04 \x01(\x0e\x32\x18.gTaskmanager.TaskStatus\x12\x0f\n\x07\x64ueDate\x18\x05 \x01(\t*;\n\nTaskStatus\x12\r\n\tPROCESSED\x10\x00\x12\x0f\n\x0b\x44ISCREPANCY\x10\x01\x12\r\n\tCOMPLETED\x10\x02\x32\xb6\x02\n\x0bTaskService\x12;\n\nCreateTask\x12\x19.gTaskmanager.TaskDetails\x1a\x10.gTaskmanager.ID\"\x00\x12\x38\n\x07GetTask\x12\x10.gTaskmanager.ID\x1a\x19.gTaskmanager.TaskDetails\"\x00\x12;\n\nUpdateTask\x12\x19.gTaskmanager.TaskDetails\x1a\x10.gTaskmanager.ID\"\x00\x12\x32\n\nDeleteTask\x12\x10.gTaskmanager.ID\x1a\x10.gTaskmanager.ID\"\x00\x12?\n\tListTasks\x12\x13.gTaskmanager.Empty\x1a\x19.gTaskmanager.TaskDetails\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TASKSTATUS']._serialized_start=208
  _globals['_TASKSTATUS']._serialized_end=267
  _globals['_EMPTY']._serialized_start=28
  _globals['_EMPTY']._serialized_end=35
  _globals['_ID']._serialized_start=37
  _globals['_ID']._serialized_end=57
  _globals['_TASKDETAILS']._serialized_start=60
  _globals['_TASKDETAILS']._serialized_end=206
  _globals['_TASKSERVICE']._serialized_start=270
  _globals['_TASKSERVICE']._serialized_end=580
# @@protoc_insertion_point(module_scope)
